/*Catégorie Client*/
INSERT INTO CategorieClient(identifiantCategorieClient, nomCategorieClient) VALUES (1, "DJ")
INSERT INTO CategorieClient(identifiantCategorieClient, nomCategorieClient) VALUES (2, "Professeur de musique")
INSERT INTO CategorieClient(identifiantCategorieClient, nomCategorieClient) VALUES (3, "Musicien amateur")
INSERT INTO CategorieClient(identifiantCategorieClient, nomCategorieClient) VALUES (4, "Musicien professionel")
INSERT INTO CategorieClient(identifiantCategorieClient, nomCategorieClient) VALUES (5, "Débutant")
INSERT INTO CategorieClient(identifiantCategorieClient, nomCategorieClient) VALUES (6, "Association")
INSERT INTO CategorieClient(identifiantCategorieClient, nomCategorieClient) VALUES (7, "Ecole de musique")
INSERT INTO CategorieClient(identifiantCategorieClient, nomCategorieClient) VALUES (8, "VIP")
INSERT INTO CategorieClient(identifiantCategorieClient, nomCategorieClient) VALUES (9, "Magasin physique")
INSERT INTO CategorieClient(identifiantCategorieClient, nomCategorieClient) VALUES (10, "Autres")